---
- name: working with secret
  hosts: all
  vars_files:
    - mysecret.yaml
  tasks:
    -name: working with secret from vault
      command: echo "the username is {{ db_user }} nad password is {{ db_passwd }}"
